# Trees & Graphs Cheat Sheet 🌳\n\n## Tree Node Definition\n\n```python\nclass TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n```\n\n## Tree Traversals\n\n### Inorder (Left-Root-Right)\n```python\ndef inorder(root):\n    if not root:\n        return []\n    return inorder(root.left) + [root.val] + inorder(root.right)\n# For BST: gives sorted order\n# Time: O(n), Space: O(h)\n```\n\n### Preorder (Root-Left-Right)\n```python\ndef preorder(root):\n    if not root:\n        return []\n    return [root.val] + preorder(root.left) + preorder(root.right)\n# Used for: copying tree, serialization\n```\n\n### Level Order (BFS)\n```python\nfrom collections import deque\ndef levelOrder(root):\n    result, queue = [], deque([root])\n    while queue:\n        level = []\n        for _ in range(len(queue)):\n            node = queue.popleft()\n            level.append(node.val)\n            if node.left: queue.append(node.left)\n            if node.right: queue.append(node.right)\n        result.append(level)\n    return result\n# Time: O(n), Space: O(w) - max width\n```\n\n## DFS & BFS\n\n### DFS (Depth-First)\n```python\ndef dfs(graph, node, visited=None):\n    if visited is None:\n        visited = set()\n    visited.add(node)\n    for neighbor in graph[node]:\n        if neighbor not in visited:\n            dfs(graph, neighbor, visited)\n    return visited\n# Time: O(V+E), Space: O(V)\n```\n\n### BFS (Breadth-First)\n```python\nfrom collections import deque\ndef bfs(graph, start):\n    visited, queue = {start}, deque([start])\n    while queue:\n        node = queue.popleft()\n        for neighbor in graph[node]:\n            if neighbor not in visited:\n                visited.add(neighbor)\n                queue.append(neighbor)\n    return visited\n# Time: O(V+E), Space: O(V)\n```\n\n## Tree & Graph Problems\n\n### Trees\n- [Binary Tree Level Order](https://leetcode.com/problems/binary-tree-level-order-traversal/)\n- [Lowest Common Ancestor](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/)\n- [Validate BST](https://leetcode.com/problems/validate-binary-search-tree/)\n- [Invert Binary Tree](https://leetcode.com/problems/invert-binary-tree/)\n\n### Graphs\n- [Number of Islands](https://leetcode.com/problems/number-of-islands/)\n- [Course Schedule](https://leetcode.com/problems/course-schedule/)\n- [Clone Graph](https://leetcode.com/problems/clone-graph/)\n"
  },
    "message": "cheat: add trees and graphs cheat sheet",
    "owner": "chandusriii",
    "path": "cheat-sheets/trees-graphs.md",
    "repo": "dsa-365"
  },
  {
    "path": "problems/01-arrays/002-best-time-to-buy-stock.py",
    "content": "\"\"\"\nProblem: Best Time to Buy and Sell Stock\nLink: https://leetcode.com/problems/best-time-to-buy-and-sell-stock/\nDifficulty: Easy\n\nYou are given array prices where prices[i] is price on day i.\nMaximize profit by choosing a day to buy and a future day to sell.\nReturn maximum profit you can achieve.\n\nExample:\n    Input: prices = [7,1,5,3,6,4]\n    Output: 5\n    Explanation: Buy at 1, sell at 6\n\nApproach: Single Pass\nTime Complexity: O(n)\nSpace Complexity: O(1)\n\"\"\"\n\nfrom typing import List\n\n\nclass Solution:\n    def maxProfit(self, prices: List[int]) -> int:\n        min_price = prices[0]\n        max_profit = 0\n        \n        for price in prices[1:]:\n            potential_profit = price - min_price\n            max_profit = max(max_profit, potential_profit)\n            min_price = min(min_price, price)\n        \n        return max_profit\n\n\ndef test():\n    sol = Solution()\n    assert sol.maxProfit([7,1,5,3,6,4]) == 5\n    assert sol.maxProfit([7,6,4,3,1]) == 0\n    assert sol.maxProfit([1,2,3,4,5]) == 4\n    print(\"✅ All tests passed!\")\n\n\nif __name__ == \"__main__\":\n    test()\n"
  },
  {
    "path": "problems/01-arrays/003-contains-duplicate.py",
    "content": "\"\"\"\nProblem: Contains Duplicate\nLink: https://leetcode.com/problems/contains-duplicate/\nDifficulty: Easy\n\nGiven an integer array, return true if any value appears at least twice.\nReturn false if every element is distinct.\n\nExample:\n    Input: nums = [1,2,3,1]\n    Output: true\n\nApproach: Hash Set\nTime Complexity: O(n)\nSpace Complexity: O(n)\n\"\"\"\n\nfrom typing import List\n\n\nclass Solution:\n    def containsDuplicate(self, nums: List[int]) -> bool:\n        seen = set()\n        for num in nums:\n            if num in seen:\n                return True\n            seen.add(num)\n        return False\n\n\ndef test():\n    sol = Solution()\n    assert sol.containsDuplicate([1,2,3,1]) == True\n    assert sol.containsDuplicate([1,2,3,4]) == False\n    print(\"✅ All tests passed!\")\n\n\nif __name__ == \"__main__\":\n    test()\n"
  },
  {
    "path": "problems/02-strings/001-valid-parentheses.py",
    "content": "\"\"\"\nProblem: Valid Parentheses\nLink: https://leetcode.com/problems/valid-parentheses/\nDifficulty: Easy\n\nGiven a string with brackets, determine if it's valid.\nOpen brackets must close in correct order.\n\nExample:\n    Input: s = \"()\"\n    Output: true\n    Input: s = \"([{}])\"\n    Output: true\n\nApproach: Stack\nTime Complexity: O(n)\nSpace Complexity: O(n)\n\"\"\"\n\nfrom collections import deque\n\n\nclass Solution:\n    def isValid(self, s: str) -> bool:\n        closing_to_opening = {')': '(', '}': '{', ']': '['}\n        stack = deque()\n        \n        for char in s:\n            if char in closing_to_opening:\n                if not stack or stack.pop() != closing_to_opening[char]:\n                    return False\n            else:\n                stack.append(char)\n        \n        return len(stack) == 0\n\n\ndef test():\n    sol = Solution()\n    assert sol.isValid(\"()\") == True\n    assert sol.isValid(\"([{}])\") == True\n    assert sol.isValid(\"(]\") == False\n    assert sol.isValid(\"\") == True\n    print(\"✅ All tests passed!\")\n\n\nif __name__ == \"__main__\":\n    test()\n"
  },
  {
    "path": "problems/02-strings/002-longest-substring-without-repeating.py",
    "content": "\"\"\"\nProblem: Longest Substring Without Repeating Characters\nLink: https://leetcode.com/problems/longest-substring-without-repeating-characters/\nDifficulty: Medium\n\nFind the length of the longest substring without repeating characters.\n\nExample:\n    Input: s = \"abcabcbb\"\n    Output: 3 (\"abc\")\n\nApproach: Sliding Window\nTime Complexity: O(n)\nSpace Complexity: O(m) where m is charset size\n\"\"\"\n\n\nclass Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        char_index = {}\n        left = 0\n        max_length = 0\n        \n        for right in range(len(s)):\n            char = s[right]\n            if char in char_index and char_index[char] >= left:\n                left = char_index[char] + 1\n            char_index[char] = right\n            max_length = max(max_length, right - left + 1)\n        \n        return max_length\n\n\ndef test():\n    sol = Solution()\n    assert sol.lengthOfLongestSubstring(\"abcabcbb\") == 3\n    assert sol.lengthOfLongestSubstring(\"bbbbb\") == 1\n    assert sol.lengthOfLongestSubstring(\"abcdefg\") == 7\n    print(\"✅ All tests passed!\")\n\n\nif __name__ == \"__main__\":\n    test()\n"
  },
  {
    "path": "problems/03-linked-lists/001-reverse-linked-list.py",
    "content": "\"\"\"\nProblem: Reverse Linked List\nLink: https://leetcode.com/problems/reverse-linked-list/\nDifficulty: Easy\n\nGiven the head of a singly linked list, reverse it.\n\nExample:\n    Input: head = [1,2,3,4,5]\n    Output: [5,4,3,2,1]\n\nApproach: Iterative\nTime Complexity: O(n)\nSpace Complexity: O(1)\n\"\"\"\n\nfrom typing import Optional\n\n\nclass ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\n\nclass Solution:\n    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:\n        prev = None\n        current = head\n        \n        while current:\n            next_temp = current.next\n            current.next = prev\n            prev = current\n            current = next_temp\n        \n        return prev\n\n\ndef create_list(values):\n    if not values:\n        return None\n    head = ListNode(values[0])\n    current = head\n    for val in values[1:]:\n        current.next = ListNode(val)\n        current = current.next\n    return head\n\n\ndef to_list(head):\n    result = []\n    while head:\n        result.append(head.val)\n        head = head.next\n    return result\n\n\ndef test():\n    sol = Solution()\n    head = create_list([1,2,3,4,5])\n    assert to_list(sol.reverseList(head)) == [5,4,3,2,1]\n    print(\"✅ All tests passed!\")\n\n\nif __name__ == \"__main__\":\n    test()\n"
  },
  {
    "path": "problems/07-dynamic-programming/001-climbing-stairs.py",
    "content": "\"\"\"\nProblem: Climbing Stairs\nLink: https://leetcode.com/problems/climbing-stairs/\nDifficulty: Easy\n\nYou are climbing stairs with n steps.\nEach time climb 1 or 2 steps. How many distinct ways to reach the top?\n\nExample:\n    Input: n = 3\n    Output: 3 (\"1+1+1\", \"1+2\", \"2+1\")\n\nApproach: Dynamic Programming\nTime Complexity: O(n)\nSpace Complexity: O(1)\n\"\"\"\n\n\nclass Solution:\n    def climbStairs(self, n: int) -> int:\n        if n <= 2:\n            return n\n        \n        prev2, prev1 = 1, 2\n        for i in range(3, n + 1):\n            current = prev1 + prev2\n            prev2 = prev1\n            prev1 = current\n        \n        return prev1\n\n\ndef test():\n    sol = Solution()\n    assert sol.climbStairs(1) == 1\n    assert sol.climbStairs(2) == 2\n    assert sol.climbStairs(3) == 3\n    assert sol.climbStairs(4) == 5\n    print(\"✅ All tests passed!\")\n\n\nif __name__ == \"__main__\":\n    test()\n"
  }
]